version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - type: bind
        source: ${SSH_AUTH_SOCK}
        target: /ssh-agent
    environment:
      SSH_AUTH_SOCK: /ssh-agent

    command: sleep infinity

    ports:
      - 3000:3000
      - 5000:5000
      - 8080:8080

    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-dash:
    image: postgres:latest
    volumes:
      - apoioz-dash-database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 1212:1212
    command: -p 1212
    extra_hosts:
      - host.docker.internal:host-gateway

  db-wa:
    image: postgres:latest
    volumes:
      - apoioz-wa-database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 1213:1213
    command: -p 1213
    extra_hosts:
      - host.docker.internal:host-gateway

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  apoioz-dash-database:
  apoioz-wa-database:
