import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PanelSideBar from "../../common/components/panelSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <main>
      <PanelSideBar content={children} />
    </main>
  );
}
